import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

import { ESLint } from 'eslint';
import tseslint from 'typescript-eslint';
import { describe, expect, it } from 'vitest';

import { LAYERS, layerConfigs } from '../../eslint.config.mjs';

/**
 * The layering rule is only worth having if it fires, and for its first commit it
 * did not: imports carry an explicit `.js` extension under nodenext, so a bare
 * `**\/plugin` pattern never matched `../plugin.js`. The rule looked enforced and
 * enforced nothing.
 *
 * These cases lint against the real exported layer configs. Type-aware linting needs
 * files that exist on disk, so the parser is swapped for the untyped one --
 * no-restricted-imports is syntactic and does not need type information.
 */
const eslint = new ESLint({
    overrideConfigFile: true,
    overrideConfig: [
        { files: ['**/*.ts'], languageOptions: { parser: tseslint.parser } },
        ...layerConfigs,
    ] as ESLint.Options['overrideConfig'],
});

async function restricted(filePath: string, code: string): Promise<string[]> {
    const [result] = await eslint.lintText(`${code}\nexport const value = 1;\n`, { filePath });
    const messages = result?.messages ?? [];
    const fatal = messages.filter((m) => m.fatal);
    if (fatal.length > 0) throw new Error(`lint could not parse ${filePath}: ${fatal[0]?.message ?? ''}`);
    return messages.filter((m) => m.ruleId === 'no-restricted-imports').map((m) => m.message);
}

describe('layer boundaries are enforced', () => {
    it.each([
        ['src/storage/x.ts', "import { PluginRegistry } from '../plugin.js';"],
        ['src/storage/x.ts', "import { WMEventEmitter } from '../events/emitter.js';"],
        ['src/storage/x.ts', "import { resolveDisconnectCause } from '../compat/baileys.js';"],
        ['src/storage/deep/y.ts', "import { PluginRegistry } from '../../plugin.js';"],
        ['src/auth/x.ts', "import { PluginRegistry } from '../plugin.js';"],
        ['src/events/x.ts', "import { memoryStorage } from '../storage/memory.js';"],
        ['src/messaging/x.ts', "import { memoryStorage } from '../storage/memory.js';"],
        ['src/utils/x.ts', "import { WMEventEmitter } from '../events/emitter.js';"],
        ['src/generated/x.ts', "import { silentLogger } from '../logger.js';"],
    ])('%s cannot import %s', async (filePath, code) => {
        expect(await restricted(filePath, code)).not.toEqual([]);
    });

    it.each([
        ['src/storage/x.ts', "import { WhatsMultiError } from '../errors.js';"],
        ['src/storage/x.ts', "import { silentLogger } from '../logger.js';"],
        ['src/storage/x.ts', "import { SESSION_STATES } from '../generated/index.js';"],
        ['src/auth/x.ts', "import { memoryStorage } from '../storage/memory.js';"],
        ['src/events/x.ts', "import { WhatsMultiError } from '../errors.js';"],
        ['src/session/x.ts', "import { memoryStorage } from '../storage/memory.js';"],
    ])('%s may import %s', async (filePath, code) => {
        expect(await restricted(filePath, code)).toEqual([]);
    });

    it('declares a rule for every layer, plus the generated-directory rule', () => {
        expect(layerConfigs).toHaveLength(Object.keys(LAYERS).length + 1);
        for (const config of layerConfigs) {
            expect(config.rules?.['no-restricted-imports']).toBeDefined();
        }
    });

    it('lets the generated barrel re-export its own siblings', async () => {
        // Restricting src/generated by path rather than by layer name is what keeps
        // `export * from './errors.js'` legal inside it.
        expect(await restricted('src/generated/index.ts', "export * from './errors.js';")).toEqual([]);
    });

    it('generates a pattern that survives the .js extension', () => {
        // The specific shape that was missing. Kept explicit so a future refactor of
        // the pattern builder cannot quietly reintroduce it.
        const patterns = (layerConfigs[0]?.rules?.['no-restricted-imports'] as [string, { patterns: string[] }])[1]
            .patterns;
        expect(patterns.some((p) => p.endsWith('.js'))).toBe(true);
    });
});

/**
 * The layer rules above police our own directories. This one polices the driver
 * itself: Baileys is on the 7.0.0-rc line and can break between release candidates,
 * so an RC bump has to stay a one-directory diff. ESLint cannot express it without
 * clobbering the per-directory `no-restricted-imports` above, so it is a test.
 */
describe('driver containment', () => {
    const PEER = '@whiskeysockets/baileys';

    const sourceFiles = (dir: string): string[] =>
        readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
            const path = join(dir, entry.name);
            if (entry.isDirectory()) return sourceFiles(path);
            return entry.name.endsWith('.ts') ? [path] : [];
        });

    const importers = sourceFiles('src').filter((file) => readFileSync(file, 'utf8').includes(PEER));

    it('confines every reference to the driver to src/compat', () => {
        expect(importers.filter((file) => !file.startsWith(join('src', 'compat')))).toEqual([]);
    });

    it('finds references inside src/compat, so the check is not vacuous', () => {
        expect(importers.length).toBeGreaterThan(0);
    });

    it('keeps the driver out of the static module graph', () => {
        // Every static import of Baileys must be type-only, so importing the package
        // to read a constant or build a storage adapter does not load the driver.
        // src/compat/driver.ts reaches it through a dynamic import instead.
        const clauses = importers.flatMap((file) => [
            ...readFileSync(file, 'utf8').matchAll(/^import\s+([\s\S]*?)from '@whiskeysockets\/baileys';/gm),
        ]);

        expect(clauses.length).toBeGreaterThan(0);
        for (const [, clause] of clauses) {
            expect(clause?.trimStart().startsWith('type')).toBe(true);
        }
    });
});
