import { createHmac } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import {
    DEFAULT_TOLERANCE_SECONDS,
    parseSignatureHeader,
    signPayload,
    signedPayload,
    verifySignature,
} from '../../src/webhook/signature.js';

interface Vector {
    readonly secret: string;
    readonly toleranceSeconds: number;
    readonly cases: readonly { t: number; body: string; signedPayload: string; v1: string; header: string }[];
}

const vector = JSON.parse(
    readFileSync(join(process.cwd(), 'spec', 'vectors', 'webhook-signature.json'), 'utf8')
) as Vector;

const SECRET = vector.secret;

/**
 * The gate for this phase. These are the same bytes the Go build signs; a difference
 * here is a receiver that accepts one runtime and rejects the other.
 */
describe('spec/vectors/webhook-signature.json', () => {
    it.each(vector.cases.map((c, i) => [i, c] as const))('case %i signs to the pinned value', (_i, c) => {
        expect(signedPayload(c.t, c.body)).toBe(c.signedPayload);
        const signature = signPayload(SECRET, c.body, c.t);
        expect(signature.v1).toBe(c.v1);
        expect(signature.header).toBe(c.header);
        expect(signature.t).toBe(c.t);
    });

    it.each(vector.cases.map((c, i) => [i, c] as const))('case %i verifies against its own header', (_i, c) => {
        expect(verifySignature({ body: c.body, header: c.header, secret: SECRET, now: () => c.t * 1000 })).toBe(true);
    });

    it('matches the tolerance the spec recommends', () => {
        expect(DEFAULT_TOLERANCE_SECONDS).toBe(vector.toleranceSeconds);
    });

    it('is the algorithm spelled out in the document, not just in the fixture', () => {
        // Recomputed independently of signPayload: a fixture regenerated by the same
        // helper it tests proves only that the helper is deterministic.
        const c = vector.cases[0]!;
        const expected = createHmac('sha256', SECRET).update(`${c.t}.${c.body}`).digest('hex');
        expect(expected).toBe(c.v1);
    });
});

describe('parseSignatureHeader', () => {
    it('reads t and v1 in either order', () => {
        expect(parseSignatureHeader('t=17,v1=abcd')).toEqual({ t: 17, v1: 'abcd' });
        expect(parseSignatureHeader('v1=abcd,t=17')).toEqual({ t: 17, v1: 'abcd' });
    });

    it('tolerates whitespace and unknown fields', () => {
        // A future scheme dual-signs with v2 beside v1. A parser that rejected the
        // whole header would break on the day the sender starts doing it.
        expect(parseSignatureHeader(' t=17 , v2=zz , v1=abcd ')).toEqual({ t: 17, v1: 'abcd' });
    });

    it('splits on the first = only', () => {
        expect(parseSignatureHeader('t=17,v1=ab=cd')).toEqual({ t: 17, v1: 'ab=cd' });
    });

    it.each([
        ['', 'empty'],
        ['v1=abcd', 'no timestamp'],
        ['t=17', 'no signature'],
        ['t=notanumber,v1=abcd', 'non-numeric timestamp'],
        ['t=1.5,v1=abcd', 'fractional timestamp'],
        ['nonsense', 'no separator at all'],
    ])('rejects %s (%s)', (header) => {
        expect(parseSignatureHeader(header)).toBeNull();
    });
});

describe('verifySignature', () => {
    const body = '{"specVersion":"x","instanceId":"i","events":[]}';
    const t = 1_755_500_000;
    const now = () => t * 1000;
    const header = signPayload(SECRET, body, t).header;

    it('rejects a body that changed by one byte', () => {
        expect(verifySignature({ body: `${body} `, header, secret: SECRET, now })).toBe(false);
    });

    it('rejects the wrong secret', () => {
        expect(verifySignature({ body, header, secret: 'other', now })).toBe(false);
    });

    it('rejects a signature lifted from a different timestamp', () => {
        // The timestamp is inside the MAC, so re-labelling it invalidates it. This is
        // what stops a captured request from being replayed with a fresh `t`.
        const forged = `t=${t + 1},v1=${signPayload(SECRET, body, t).v1}`;
        expect(verifySignature({ body, header: forged, secret: SECRET, now: () => (t + 1) * 1000 })).toBe(false);
    });

    it('rejects an unparseable header', () => {
        expect(verifySignature({ body, header: 'garbage', secret: SECRET, now })).toBe(false);
    });

    it.each([
        ['short', 'v1=ab'],
        ['odd length', 'v1=abc'],
        ['not hex at all', 'v1=zzzz'],
    ])('rejects a malformed signature (%s) without throwing', (_label, v1) => {
        // Buffer.from(_, 'hex') decodes short instead of throwing, so the length check
        // has to come before timingSafeEqual -- which throws on mismatched lengths.
        expect(verifySignature({ body, header: `t=${t},${v1}`, secret: SECRET, now })).toBe(false);
    });

    it('rejects a stale timestamp', () => {
        const late = () => (t + DEFAULT_TOLERANCE_SECONDS + 1) * 1000;
        expect(verifySignature({ body, header, secret: SECRET, now: late })).toBe(false);
    });

    it('rejects a timestamp too far in the future', () => {
        // Symmetric on purpose: a receiver whose clock runs behind would otherwise
        // accept requests dated arbitrarily far ahead, and the replay window would
        // never close.
        const early = () => (t - DEFAULT_TOLERANCE_SECONDS - 1) * 1000;
        expect(verifySignature({ body, header, secret: SECRET, now: early })).toBe(false);
    });

    it('accepts a timestamp exactly on the tolerance boundary', () => {
        const edge = () => (t + DEFAULT_TOLERANCE_SECONDS) * 1000;
        expect(verifySignature({ body, header, secret: SECRET, now: edge })).toBe(true);
    });

    it('honours a custom tolerance', () => {
        const late = () => (t + 10) * 1000;
        expect(verifySignature({ body, header, secret: SECRET, toleranceSeconds: 5, now: late })).toBe(false);
        expect(verifySignature({ body, header, secret: SECRET, toleranceSeconds: 60, now: late })).toBe(true);
    });

    it('skips the freshness check when the tolerance is zero', () => {
        const ages = () => (t + 10_000_000) * 1000;
        expect(verifySignature({ body, header, secret: SECRET, toleranceSeconds: 0, now: ages })).toBe(true);
    });

    it('defaults to the real clock', () => {
        const fresh = signPayload(SECRET, body, Math.floor(Date.now() / 1000)).header;
        expect(verifySignature({ body, header: fresh, secret: SECRET })).toBe(true);
    });
});
